import { join } from 'node:path'
import { GeneratorCommand } from '@elysian/console'
import { Str } from '@elysian/support'

export class MakeModelCommand extends GeneratorCommand {
  static override signature =
    'make:model {name : Model class name, e.g. Post} {--m|migration : Also create a migration} {--f|factory : Also create a factory} {--s|seeder : Also create a seeder} {--force : Overwrite an existing file}'

  static override description = 'Create a new model'

  protected stub(): string {
    return 'model.stub'
  }

  protected type(): string {
    return 'Model'
  }

  protected destination(name: string): string {
    return this.app.appPath('Models', `${this.className(name)}.ts`)
  }

  protected override className(name: string): string {
    return Str.studly(this.baseName(name))
  }

  protected override replacements(name: string): Record<string, string> {
    const model = this.className(name)

    return {
      ...super.replacements(name),
      table: Str.snake(Str.plural(model))
    }
  }

  override async handle(): Promise<number> {
    const status = await super.handle()
    if (status !== 0) return status

    const model = this.className(this.argument('name'))

    // The companion files are generated by their own commands, so their stubs
    // stay in one place.
    if (this.flag('migration')) {
      await this.call('make:migration', [`create_${Str.snake(Str.plural(model))}_table`])
    }
    if (this.flag('factory')) await this.call('make:factory', [`${model}Factory`, '--model', model])
    if (this.flag('seeder')) await this.call('make:seeder', [`${model}Seeder`])

    return 0
  }

  /** Stubs live in this package, not in @elysian/console. */
  protected override async readStub(): Promise<string> {
    const published = Bun.file(this.app.basePath('stubs', this.stub()))
    if (await published.exists()) return published.text()

    return Bun.file(join(import.meta.dir, '..', '..', 'stubs', this.stub())).text()
  }
}
