import { mkdir, readdir, unlink } from 'node:fs/promises'
import { join } from 'node:path'
import { Str } from '@elvel/support'

export type SessionData = Record<string, unknown>

/** Where a session's data lives between requests. */
export interface SessionDriver {
  read(id: string): Promise<SessionData | undefined>
  write(id: string, data: SessionData): Promise<void>
  destroy(id: string): Promise<void>
  /** Remove sessions older than `lifetime` seconds. */
  gc(lifetime: number): Promise<number>
}

/** In-memory, for tests and single-process development. */
export class MemorySessionDriver implements SessionDriver {
  private readonly store = new Map<string, { data: SessionData; touched: number }>()

  constructor(private readonly now: () => number = () => Date.now()) {}

  async read(id: string): Promise<SessionData | undefined> {
    return this.store.get(id)?.data
  }

  async write(id: string, data: SessionData): Promise<void> {
    this.store.set(id, { data, touched: this.now() })
  }

  async destroy(id: string): Promise<void> {
    this.store.delete(id)
  }

  async gc(lifetime: number): Promise<number> {
    const cutoff = this.now() - lifetime * 1000
    let removed = 0

    for (const [id, entry] of this.store) {
      if (entry.touched < cutoff) {
        this.store.delete(id)
        removed += 1
      }
    }

    return removed
  }
}

/** One JSON file per session, as Laravel's `file` driver does. */
export class FileSessionDriver implements SessionDriver {
  constructor(private readonly directory: string) {}

  private path(id: string): string {
    // The id is generated by us and hex-only, but a traversal guard is cheap.
    if (!/^[A-Za-z0-9]+$/.test(id)) throw new Error('Refusing to use an unsafe session id.')

    return join(this.directory, `${id}.json`)
  }

  async read(id: string): Promise<SessionData | undefined> {
    const file = Bun.file(this.path(id))
    if (!(await file.exists())) return undefined

    try {
      return (await file.json()) as SessionData
    } catch {
      // A truncated file is a lost session, not a crash.
      return undefined
    }
  }

  async write(id: string, data: SessionData): Promise<void> {
    await mkdir(this.directory, { recursive: true })
    await Bun.write(this.path(id), JSON.stringify(data))
  }

  async destroy(id: string): Promise<void> {
    await unlink(this.path(id)).catch(() => {})
  }

  async gc(lifetime: number): Promise<number> {
    const cutoff = Date.now() - lifetime * 1000
    let removed = 0

    let entries: string[]
    try {
      entries = await readdir(this.directory)
    } catch {
      return 0
    }

    for (const entry of entries) {
      if (!entry.endsWith('.json')) continue

      const file = Bun.file(join(this.directory, entry))
      if (file.lastModified < cutoff) {
        await unlink(join(this.directory, entry)).catch(() => {})
        removed += 1
      }
    }

    return removed
  }
}

/**
 * A session for one request.
 *
 * Flash data is the part worth reading closely: `flash()` writes a value that
 * survives exactly one further request. That is what makes redirect-with-errors
 * work, and it is implemented the way Laravel does it — a `_flash.new` list that
 * becomes `_flash.old` on the next `save()`, and is then dropped.
 */
export class Session {
  private data: SessionData = {}
  private started = false
  private destroyed = false

  /** Set by everything that writes to `data`; read by `isDirty()`. */
  private changed = false

  /** Set by `save()`. Read by the error path, which must not save twice. */
  private persisted = false

  /**
   * Reassignable, because a session can be given a new one.
   *
   * `regenerate()` is what a login should call: the id in the cookie before
   * signing in is an id somebody else may have chosen, and if it still names the
   * session afterwards then whoever chose it is now signed in as this user.
   */
  id: string

  constructor(
    id: string,
    private readonly driver: SessionDriver,
    private readonly name = 'elvel_session'
  ) {
    this.id = id
  }

  static newId(): string {
    return Str.random(40)
  }

  getName(): string {
    return this.name
  }

  async start(): Promise<this> {
    if (this.started) return this

    this.data = (await this.driver.read(this.id)) ?? {}
    this.started = true

    // A session always has a CSRF token, so a form can be rendered before
    // anything is written to it.
    if (typeof this.data._token !== 'string') this.regenerateToken()

    return this
  }

  all(): SessionData {
    return { ...this.data }
  }

  has(key: string): boolean {
    return this.data[key] !== undefined && this.data[key] !== null
  }

  exists(key: string): boolean {
    return key in this.data
  }

  get<T = unknown>(key: string, fallback?: T): T {
    return (this.data[key] as T) ?? (fallback as T)
  }

  put(key: string | SessionData, value?: unknown): this {
    if (typeof key === 'string') this.data[key] = value
    else Object.assign(this.data, key)

    this.changed = true

    return this
  }

  /** Read and forget in one step. */
  pull<T = unknown>(key: string, fallback?: T): T {
    const value = this.get<T>(key, fallback)
    this.forget(key)

    return value
  }

  /** Keep this value for the next request only. */
  flash(key: string, value: unknown = true): this {
    this.data[key] = value
    this.data['_flash.new'] = [...this.flashKeys('new').filter((k) => k !== key), key]
    this.data['_flash.old'] = this.flashKeys('old').filter((k) => k !== key)
    this.changed = true

    return this
  }

  /** Keep the current flash data for one more request. */
  reflash(): this {
    this.data['_flash.new'] = [...new Set([...this.flashKeys('new'), ...this.flashKeys('old')])]
    this.data['_flash.old'] = []
    this.changed = true

    return this
  }

  keep(keys: string[]): this {
    this.data['_flash.new'] = [...new Set([...this.flashKeys('new'), ...keys])]
    this.data['_flash.old'] = this.flashKeys('old').filter((key) => !keys.includes(key))
    this.changed = true

    return this
  }

  private flashKeys(kind: 'new' | 'old'): string[] {
    const value = this.data[`_flash.${kind}`]

    return Array.isArray(value) ? (value as string[]) : []
  }

  forget(...keys: string[]): this {
    for (const key of keys.flat()) delete this.data[key]

    this.changed = true

    return this
  }

  flush(): this {
    const token = this.data._token
    this.data = { _token: token }
    this.changed = true

    return this
  }

  token(): string {
    return String(this.data._token ?? '')
  }

  regenerateToken(): this {
    this.data._token = Str.random(40)
    this.changed = true

    return this
  }

  previousUrl(): string | undefined {
    const value = this.data._previous_url

    return typeof value === 'string' ? value : undefined
  }

  setPreviousUrl(url: string): this {
    this.data._previous_url = url

    return this
  }

  /** Drop this session's data entirely. */
  async invalidate(): Promise<void> {
    this.data = {}
    this.destroyed = true
    await this.driver.destroy(this.id)
  }

  isDestroyed(): boolean {
    return this.destroyed
  }

  /**
   * Has anything been written to this session since it was read?
   *
   * Asked by the error path, which saves what a handler would have saved — and
   * only if there is something to save. `save()` *ages* the flash data: it drops
   * what the last request flashed and promotes what this one did. So saving a
   * session nobody touched is not a harmless extra write, it consumes a message
   * that was on its way to a page.
   *
   * Measured as four smoke failures the moment the error path saved
   * unconditionally: a `419` for a missing CSRF token aged the flash a successful
   * write had just set, and the page that was going to show it read nothing. A
   * browser asking for a favicon that does not exist would have done the same.
   */
  isDirty(): boolean {
    return this.changed
  }

  /**
   * Has this session already been written during this request?
   *
   * The other half of the question above, and a different one: the error path
   * has to know both whether there is anything to save *and* whether somebody
   * already did. A redirect built with flash data persists the session itself, so
   * saving again ages what it had just promoted — the message would be gone
   * before the page meant to show it.
   */
  isPersisted(): boolean {
    return this.persisted
  }

  /**
   * A new id for the same data — what a login must do.
   *
   * Session fixation, concretely: an attacker gets a victim's browser to hold a
   * session id they already know, the victim signs in, and the id they know is now
   * an authenticated session. Nothing about the sign-in itself is broken; the id
   * simply never changed. Laravel calls this from
   * `AuthenticatedSessionController::store` for the same reason.
   *
   * The CSRF token is rotated with it. A token is bound to a session, so keeping
   * the old one across a privilege change means the value a page picked up while
   * signed out still authorises writes while signed in.
   *
   * The old record is destroyed by default, which is where this differs from
   * Laravel's `regenerate()`. What an attacker holds *is* that record — leaving it
   * to expire leaves it usable until it does. Pass `false` to keep it, for the
   * rare case where something else still reads it.
   */
  async regenerate(destroyPrevious = true): Promise<this> {
    const previous = this.id

    this.id = Session.newId()
    this.regenerateToken()

    if (destroyPrevious) await this.driver.destroy(previous)

    return this
  }

  /** Persist, ageing the flash data by one request. */
  async save(): Promise<void> {
    if (this.destroyed) return

    this.changed = false
    this.persisted = true

    // Whatever was flashed last request has now been read; drop it, and promote
    // this request's flashes into its place.
    for (const key of this.flashKeys('old')) delete this.data[key]

    this.data['_flash.old'] = this.flashKeys('new')
    this.data['_flash.new'] = []

    await this.driver.write(this.id, this.data)
  }
}

/**
 * Read the session from an Elysia context.
 *
 * The derive that puts it there is registered globally by
 * `HttpServiceProvider`, so a standalone controller cannot infer the property —
 * Elysia types a context from the plugins that instance itself uses. Rather than
 * scatter casts, the narrowing lives here, in one documented place.
 *
 * ```ts
 * .get('/me', (context) => ({ token: sessionOf(context).token() }))
 * ```
 */
export function sessionOf(context: unknown): Session {
  const session = (context as { session?: unknown }).session

  if (!(session instanceof Session)) {
    throw new Error(
      'No session on this request. Register HttpServiceProvider and keep session.enabled on.'
    )
  }

  return session
}
